import type { Metadata } from "next";
import { Lato } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const lato = Lato({
  subsets: ["latin"],
  weight: ["300", "400", "700", "900"],
});

const museo_slab = localFont({
  src: [
    {
      path: "../../public/fonts/Museo_Slab_300.otf",
      weight: "300",
      style: "light",
    },
    {
      path: "../../public/fonts/Museo_Slab_500.otf",
      weight: "500",
      style: "medium",
    },
    {
      path: "../../public/fonts/Museo_Slab_700.otf",
      weight: "700",
      style: "bold",
    },
    {
      path: "../../public/fonts/Museo_Slab_900.otf",
      weight: "900",
      style: "black",
    },
  ],
  variable: "--font-museo-slab",
});

const sailec = localFont({
  src: [
    {
      path: "../../public/fonts/sailec_regular.otf",
      weight: "400",
      style: "regular",
    },
    {
      path: "../../public/fonts/sailec_medium.ttf",
      weight: "500",
      style: "medium",
    },
    {
      path: "../../public/fonts/sailec_bold.ttf",
      weight: "700",
      style: "bold",
    },
  ],
  variable: "--font-sailec",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${lato.className} ${museo_slab.variable} ${sailec.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
